lib/puppet/provider/idrac.rb

After creation of a new virtual disk, a RAID background
initialization job will start after a few minutes to write parity
data. That operation can take hours to days to complete. The new
idrac code to monitor the virtual disk operations was blocking
waiting for that operation to complete. The virtual disk should
be usable while that operation is running, so this commit changes
the polling code to ignore the background initialization job.

ASM-2896 do not block for RAID background initialization

---

lib/puppet/provider/checkjdstatus.rb
lib/puppet/provider/checklcstatus.rb
lib/puppet/provider/exporttemplatexml.rb
spec/unit/puppet/provider/checkjdstatus_spec.rb
spec/unit/puppet/provider/exporttemplatexml_spec.rb

Migrate checkjdstatus and exporttemplatexml to use ASM::WsMan for
ws-man invocations. Previously they were directly invoking the
wsman CLI with little error handling. This change fixes problems
such as when iDrac sporadically returns erroneous 401
authentication failed errors.

ASM-2949 use ASM:WsMan for better error handling

---

lib/puppet/provider/exporttemplatexml.rb
lib/puppet/provider/idrac.rb
lib/puppet/provider/importsystemconfiguration/default.rb
lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/exporttemplatexml_spec.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb
templates/preset-config.erb

There will now be 4 files from the exports/imports.  
* <servicetag>_original.xml which contains the target server's configuration before any changes are made
* <servicetag>_preset.xml which contains basic attributes that we send in first to "preset" the idrac to be in a state that's easy for us to use.  This includes setting up partitioning, setting up boot protocol, enabling raid, enabling SD card.
* <servicetag>_base.xml which contains the configuration that will be used as the reference for the config we send to the server
* <servicetag>.xml which contains the system configuration we import to the target server.
The main part is the _preset.xml, which should allow us to enable/disable what needs to be set up on the idrac in order for the import to work as smoothly as possible.

Changed importsystemconfiguration workflow to help reliability/stability

---

lib/puppet/provider/importtemplatexml.rb

Should help brown-field cases where the server has virtual mac
addresses set. Specifically this fixes a case we saw where they
had a server with duplicate virtual mac addresses.

ASM-2857 Reset virtual mac addresses during deployment

---

lib/puppet/provider/idrac_fw_installfromuri/wsman.rb

- allow for idrac to go offline during idrac firmware update
- monitor each job individually with a max execution time of 30
minutes

ASM-3439, ASM-3444 improve idrac firmware update

---

lib/puppet/provider/idrac.rb

This change was made in 8.1 branch but never backported to 8.0

skip background configuration in virtual_disks_ready?

---

lib/puppet/provider/idrac_fw_installfromuri/wsman.rb

Should have been ASM::WsMan::Error not ASM::WsMan::StandardError

ASM-3439 wrong exception rescued in firmware retry

---

lib/puppet/provider/importsystemconfiguration/default.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

Job queue will now be cleared before we do a reboot of the server instead of after.  We will also query the LC to check that the job queue is also empty before allowing it to go on
I also fixed the tests.  yay.

Clear job queue improvements

---

lib/puppet/provider/importsystemconfiguration/default.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

Job queue will now be cleared before we do a reboot of the server instead of after.  We will also query the LC to check that the job queue is also empty before allowing it to go on

ASM-3603 Clear job queue improvements

---

lib/puppet/idrac/util.rb
lib/puppet/provider/checkjdstatus.rb
lib/puppet/provider/idrac.rb
lib/puppet/provider/importsystemconfiguration/default.rb
lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

There were also some changes to improve the code a bit 
1) We now wait for import inside of importtemplatexml.rb rather than having the object pass back the job id and waiting outside.  This is just to "compartmentalize" the import process so the code is kept more "contained"
2) Wrapped the different import calls with the retry code and cleaned that up a bit.
3) Various improvements to the setup process.  Now, we should be checking now if anything needs to change before we actually do the import.
IMPORTANT: Should be merged with https://github.com/dell-asm/asm/pull/234

ASM-3529 Added  new import to fix iscsi/fcoe offload not being set

---

lib/puppet/provider/exporttemplatexml.rb
lib/puppet/provider/importtemplatexml.rb

If nfsipaddress is not specified in the importsystemconfiguration
resource, use the current IP by default. This allows the same
configuration to function properly on any worker node.

ASM-4331 use local ip for import / export by default

---

lib/puppet/provider/importraidconfiguration/default.rb

An encrypted device password was passed to the asm-deployer device
management service and written to the device configuration file
url. That password has been deprecated and all puppet-layer code
should use the credential_id argument in preference to that.

ASM-3406 remove asm_decrypt password encryption

---

lib/puppet/provider/exporttemplatexml.rb
lib/puppet/provider/idrac.rb
spec/unit/puppet/provider/exporttemplatexml_spec.rb
tests/disablenpar.pp
tests/enablenpar.pp
tests/exportsystemconfiguration.pp
tests/importbiosconfiguration.pp
tests/importraidconfiguration.pp
tests/importsystemconfiguration.pp

This change is for 8.2, and should probably wait until then unless needed beforehand for whatever reasons.

import config should no longer rely on /var/nfs open permissions

---

lib/puppet/provider/importtemplatexml.rb

That will now be handled by separate orchestration code as not all O/S
installations will go through NIC-based PXE boot.

ASM-5219 do not add PXE to boot order

---

lib/puppet/provider/importtemplatexml.rb

Incorrect capitalization caused the attribute to be trashed before sending the import (which would have failed if we weren't trashing BIOS attributes that don't exist on the server)

ASM-3297 Fixed an issue where SD was not being disabled for BFS

---

lib/puppet/provider/importtemplatexml.rb

Don't hardcode BIOS VT settings to enabled when specifying target
boot device

ASM-5753 BIOS VT settings

---

lib/puppet/provider/importtemplatexml.rb

Logic error in VSAN changes prevented target_boot_device = "HD"
deployments from creating virtual disks.

Fix virtual disks not being created

---

lib/puppet/provider/importtemplatexml.rb

force all server deployments with SD card(s) to use Mirror redundancy mode

ASM-953 force all server deployments with SD card(s) to use Mirror redundancy mode

---

lib/puppet/idrac/util.rb

If we are resetting the idrac. We need to wait longer before timing out
when checking for the idrac to become available again

ASM-5767 Import config fails with Idrac timeout

---

lib/puppet/provider/importtemplatexml.rb

This prevents the server from booting into who-knows-what is installed
on it after the configuration is complete. Server should be manually
powered on separately when needed.

ASM-6335 Power server off after system config applied

---

lib/puppet/provider/importtemplatexml.rb

Reverts dell-asm/dell-idrac#200
This change seems to be causing an increased number of failures to set PXE in the boot order. The FQDDs in BiosBootSeq seem to be changing when the server first turns on after the ImportSystemConfiguration job was run, even though LC team reports that CSIOR is stell run with EndHostPowerState = 0.
I.e. after running an ImportSystemConfiguration job but before turning the server on I got:
[root@dellasm idrac_config_xml]# wsman_shell.rb --server 172.17.1.223
[1] pry(#<ASM::WsMan>)> boot_source_settings.map { |e| [e[:current_assigned_sequence], e[:instance_id]] }
=> [["0",
"IPL:BIOS.Setup.1-1#BootSeq#HardDisk.List.1-1#c9203080df84781e2ca3d512883dee6f"],
["1",
"IPL:BIOS.Setup.1-1#BootSeq#NIC.Integrated.1-1-1#b358f1564c3350889a9ec123cb23ad56"],
["2", …

Revert "ASM-6335 Power server off after system config applied"

---

Gemfile
lib/puppet/idrac/util.rb
lib/puppet/provider/idrac.rb
lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
lib/puppet/provider/idrac_fw_update/wsman.rb
lib/puppet/provider/idrac_racadm.rb
lib/puppet/provider/powerstate/default.rb
lib/puppet_x/puppetlabs/transport/idrac.rb
lib/puppet_x/puppetlabs/transport/racadm.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

Changing where the idrac module gets user,password,ip_address info for the transport method so that we don't depend on asm-deployer.
This needs dell-asm/asm#290

ASM-5482 removing the asm-deployer dependency

---

lib/puppet/idrac/util.rb
lib/puppet/provider/idrac.rb
lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
lib/puppet/provider/importtemplatexml.rb

We moved wait_for_lc_ready from the Idrac parent providcer Puppet::Provider::Idrac to Puppet::Idrac::Util.wait_for_lc_ready so that we can use it in Puppet::Provider::Importtemplatexml

ASM-6005 Extend idrac waits

---

lib/puppet/provider/importtemplatexml.rb

To ensure we are picking the first disk in the enumeration for OS installation

ASM-6387 ASM to support Urgent Fury vSAN RA

---

lib/puppet/provider/importtemplatexml.rb

Import configuration operation failing for VSAN with SD card in case HBA mode is not already set. This loop never got tested as we were using the servers which were atleast once configured to be used as VSAN node.
This bug got introduced while addressing the code comments. After addressing the code comments this part was not tested.

ASM-6719 Import configuration operation failing for VSAN with SD card in case HBA mode is not already set

---

Gemfile
lib/puppet/provider/importtemplatexml.rb

Included "RAIDresetconfig" attribute with the RAID controller while moving the Controller from RAID to HBA mode. This will ensure all the Virtual Disks are removed before the HBA mode is configured.
In case there is any Virtual Disk on the RAID controller, then HBA mode cannot be set.
Also, then Controller is already in HBA mode then RAIDresetconfig is not allowed by iDRAC that why we are limiting the RAIDresetconfig attribute only in case we are moving controller from RAID to HBA mode.

ASM-6720 Config XML import operation fails to set HBA mode when Virtual Disks are present

---

lib/puppet/provider/importtemplatexml.rb

HBA Mode attribute was getting overridden due to a recent change added for raid reset

ASM-6769 VSAN Deployment reports "Warning" at cluster level

---

lib/puppet/provider/idrac_fw_installfromuri/wsman.rb

8.2 changes that were made to use the ASM::WsMan library in
idrac_fw_installfromuri to fix password-handling problems weren't
compatible with 8.3 changes to use a transport resource.

ASM-6781 Fix transport in idrac_fw_installfromuri

---

lib/puppet/idrac/util.rb
lib/puppet/provider/checklcstatus.rb
lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
lib/puppet/provider/idrac_fw_update/wsman.rb
lib/puppet/provider/powerstate/default.rb
lib/puppet/provider/reboot.rb

Update ws-man URLs to use "&" as query parameter separators; wsmancli
2.6 requires this. These URLs with work earlier wsmancli versions such
as 2. 3 as well.

ASM-6558 Interoperability with wsmancli 2.6

---

lib/puppet/provider/importtemplatexml.rb

When RAID Controller is not in HBA mode, we have to set it to HBA and RAIDReset Attribute needs to be passed to ensure all the Virtual Disk and Hotspare configuration is removed.
Earlier code was trying to set the RAIDReset for all the RAID controllers which is not supported by iDRAC also initialization of the variable was not correct.

ASM-6942 VSAN iDRAC configuration fails when RAID controller mode is not in HBA Mode

---

lib/puppet/provider/importtemplatexml.rb

- Current code was looking for the first RAID component and in certain cases RAID.Embedded component was getting picked instead of RAID.Integrated
- Removed RAID.Embedded component from the input XML in case installation disk in AHCI Mode

Removed RAID.Embedded.1.1 component from input XML for VSAN deployment on back-plane disk

---

Gemfile
lib/puppet/provider/importtemplatexml.rb

If non-RAID disks exist, on teardown we need to convert
these to a RAID virtual disk so we can re-use the server

ASM-7383 Teardown of non-RAID disks

---

lib/puppet/provider/importtemplatexml.rb

The deployment teardown did not have RAID config specified in deployment.json.
As a result, asm::idrac had set raid_configuration to {}, which later on
results in nil class exception in the puppet module.
The fix is to have safety nil checks before invoking empty? method

ASM-7423 Deployment teardown throws exception in logs

---

lib/puppet/provider/importtemplatexml.rb

Sometimes when deploying OS to HD to server whose internal SD redundancy was disabled/mirror prior to import config xml, we can end up setting config xml with SD off and *some* value for SD redundancy which can cause import config job to fail.
The fix for such scenario is to explicitly remove SD related attributes
when we set SD to off for HD deployments.

ASM-7413 Remove SD card redundancy for HD deployments

---

lib/puppet/provider/importtemplatexml.rb

SD deployments don't have a `raid_configuration` resource

ASM-7592 SD deployment fix

---

lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

Previously Idrac job runs forever if the same boot sequesnce is set again. In this PR it removes the Hddseq if it is already set.

ASM-7561: removed boot Hddseq if it is already set in idrac

---

lib/puppet/provider/idrac_fw_installfromuri/wsman.rb

We shouldn't be setting the status of components to InternalTimeout
when they are already in the desired state

ASM-7643 Firmware update fails with "InternalTimeout"

---

lib/puppet/provider/importtemplatexml.rb

In case RAID group is created for boot_device "HD" then HddSeq value is getting set even though it is already set.

ASM-7561 HddSeq set when unneeded triggers iDrac bug causing import to run forever

---

lib/puppet/idrac/util.rb
lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

As per requirement, we prefer SATADOM disk when retrieving SATA disks
for AHCI VSAN mode.

ASM-7503 IDRAC changes to support SATADOM boot drive option

---

lib/puppet/provider/importtemplatexml.rb

Problem:
In the raid_configuration, if there are no RAID config to process (like
SATADOM) the unprocessed hash may be empty, resulting into any looked up
value in this hash as nil e.g. unprocessed['virtualDisks']. Accessing
methods from looked up value results into nil class exception.
Solution:
The check for determining "no RAID config needed" needs to include empty
hash check along with nil value check.

ASM-7503 Fix teardown NilClass exception when there are no RAID disks

---

.gitignore
lib/puppet/provider/importtemplatexml.rb
spec/fixtures/BARTAG_original.xml
spec/fixtures/FOOTAG_original.xml
spec/unit/puppet/provider/importtemplatexml_spec.rb

Allow deployments to S130 embedded RAID card when that card is selected.
If the Embedded controller is currently in a mode other than "RaidMode"
we will have to configure that first before we can do any other configurations.
This will result in 2 passes of the import system config

ASM-7744 Support for RAID on S130

---

lib/puppet/provider/importtemplatexml.rb

Deployments that do not contain a raid configuration will cause
failures due to null pointer.  This fixes that

ASM-8013 Fix nil:NilClass for embedded raid check

---

.fixtures.yml
Rakefile
lib/puppet/provider/idrac_racadm.rb
lib/puppet/provider/server_onboard/default.rb
lib/puppet/type/server_onboard.rb
spec/spec_helper_ext.rb
spec/unit/puppet/provider/idrac_racadm_spec.rb
spec/unit/puppet/provider/server_onboard/server_onboard_spec.rb

Implementation for new type and provider for configuring credentials
and network settings for a given server using racadm commands. We keep
same style of implementation as we did for blades in dell-cmc module,
except for the fact the racadm calls here go directly to the server.
We also clean up and yard doc some execution methods in racadm.rb
Note: Maybe we should later refactor the code to move racadm command
to a common project where eventually all racadm calls for servers go to
single place. Right now some code is unnecessarily duplicated between
racadm.rb in dell-cmc and dell-idrac modules.

ASM-7905 Puppet provider for server onboarding

---

Rakefile

Seems recent changes in a dependent project triggered puppet-lint gem to be
installed and task as a result invoke rspec task which is expected not
to work. We fix this problem by using "spec" task for pupet-lint gem

misc: Fix travis CI problems introduced by dependencies

---

lib/puppet/provider/importsystemconfiguration/default.rb
lib/puppet/provider/importtemplatexml.rb
spec/fixtures/mock_nfs/EXPORT_original.xml

There is currently a bug when doing S130 RAID 1 where we cannot
clear the config and create the virtual disk on the same run.
Because of this, we will first run the importtemplate with an
`embedded_change` flag which will skip any raid creation and
only change the EmbMode and tear down raid

ASM-8143 Embedded RAID Support 2

---

lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

Due to presence of non-raid disk on the server, Virtual disk created for OS installation is not available at "0" disk id. To take care of this we are disabling non-raid disks from the server so that they are not available to the server.
This will also take care of the case where server has non-raid disks created from some prior deployments it is not requested in the existing deployment.

ASM-7589 Win2012R2 Deployment Failed with Error "Unable to create new partition or locate existing partition"

---

lib/puppet/provider/importtemplatexml.rb

With recent changes for converting the non-RAID disk to RAID mode, VSAN and SD card deployment got broken as there is no raid_confiuraiton parameter in the asm::idrac resource

ASM-8257 iDRAC configuation failing for VSAN and SD card deployments

---

lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

Changed the logic when gathering the current BiosBootSeq and HddSeq
to actually call out to the Lifecycle controller.
The reason for this being that we were previously comparing what
we wanted to set these attributes to against the original exported config xml
from before we ran any importconfig jobs.  This can sometimes result
in differences between the current config and the exported config
on subsequent import jobs.
If we thought the HddSeq or the BiosBootSeq were out of synce but
actually were not, we would mistakenly try to set this values
and create errors in the lifecycle controller

ASM-8106 SD Deployment with SD Disabled fails

---

lib/puppet_x/puppetlabs/transport/racadm.rb

We set paranoid param in other transport modules dealing with SSH to
ensure not getting cert errors on servers when something on server
changes. Seems this transport did not have the same paranoid param.

ASM-8239 Fix Net::SSH::HostKeyMismatch in racadm transport

---

lib/puppet/provider/importsystemconfiguration/default.rb
lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

Even though we were doing a lookup on the current HDDSeq and
BIOSBootSeq (not using the export xml)  We were only generating
the config xml one time.  Not we will regenerate the config xml
on every importsystemconfig run and rotate the old config (should
only be max of 3)

ASM-8438 ImportSystemConfig runs forever

---

lib/puppet/provider/importsystemconfiguration/default.rb

When IDRAC trying to apply import system configuration settings sometimes  configurations will be not be in sync so IDRAC will try to apply settings for couple of times. 
The below change will try to keep it in sync by trying applying configuration settings for four times,

ASM-8442 IDRAC able to try importsystemconfiguration for 4 times

---

lib/puppet/provider/importtemplatexml.rb

iDrac versions before 2.40.40.40 had a bug where if the HddSeq or
BiosBootSeq is set but not changed from it's current value the
resulting ImportSystemConfiguration job will run forever. The
workaround is to not pass those values if no change is
required. Various fixes have been put in for this issue but problems
keep cropping back up -- the whole importsystemconfiguration flow
needs a rework.
The current problem arises because the importsystemconfiguration
provider reuses the same Importtemplatexml object to retry the
ImportSystemConfiguration if it fails the first time. In that case
xml_base will be set to the XML that was applied in the first pass
rather than the original iDrac system configuration as seen from
ExportSystemConfiguration. Because of that it could contain HddSeq or …

ASM-8438 Do not set existing Hdd or BiosBoot seq

---

lib/puppet/provider/checkjdstatus.rb
lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/checkjdstatus_spec.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

Existing ImportSystemConfiguration job polling would exit early
(before the job says that it is 100% complete) in the case of
failure. Because of that and the fact that Importtemplatexml did not
wait for LC ready prior to cacluating the configuration to apply it
was possible that a previous ImportSystemConfiguration job was in
progress when a new import was begun. Therefore code that was
checking iDrac inventory might be getting values that would change
as the result of a previously running job. This could lead to the
dreaded "ImportSystemConfiguration job runs forever" bug which
happens in iDrac prior to 2.40.40.40 when a BiosBootSeq or HddSeq
is set to a pre-existing value (i.e. not changed).
This commit attempts to fix this by:
- waiting for LC ready prior to calculating the …

ASM-8548 Wait for failed import jobs to complete

---

lib/puppet/provider/checkjdstatus.rb
lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/checkjdstatus_spec.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

Existing ImportSystemConfiguration job polling would exit early
(before the job says that it is 100% complete) in the case of
failure. Because of that and the fact that Importtemplatexml did not
wait for LC ready prior to cacluating the configuration to apply it
was possible that a previous ImportSystemConfiguration job was in
progress when a new import was begun. Therefore code that was
checking iDrac inventory might be getting values that would change
as the result of a previously running job. This could lead to the
dreaded "ImportSystemConfiguration job runs forever" bug which
happens in iDrac prior to 2.40.40.40 when a BiosBootSeq or HddSeq
is set to a pre-existing value (i.e. not changed).
This commit attempts to fix this by:
- waiting for LC ready prior to calculating the …

ASM-8438, ASM-8545 Wait for failed import jobs to complete

---

Gemfile
lib/puppet/provider/importtemplatexml.rb

For VSAN deployment of SD card, HBA mode configuration was getting skipped as empty RAID configuration is passed from asm-deployer

ASM-6823 Ability to place Raid Mode into pass-through with Hardware configuration only

---

lib/puppet/provider/importtemplatexml.rb

ActiveSupport's `Hash.from_xml` started failing in
`find_target_bios_setting` after recent ruby and gem upgrades with the
error `String can't be coerced into Integer`. Changed this method to
use `ASM::WsMan#bios_enumerations` which already has parsing for
this. Note that the return value of `find_target_bios_setting` has
changed slightly but all callers only use the return value to check
whether it is `nil` or not.

LUD-94 Fix XML parsing issue introduced by version upgrades

---

lib/puppet/provider/importtemplatexml.rb
spec/fixtures/boot_sources.json
spec/fixtures/satadom_boot_sources.json
spec/unit/puppet/provider/importtemplatexml_spec.rb

Add support for SATADOM for LOCAL_FLASH_STORAGE target boot device.  Should be merged with PR:
https://github.com/dell-asm/razor-server/pull/145

LUD-135 Add support for SATADOM for LOCAL_FLASH_STORAGE

---

lib/puppet/provider/importtemplatexml.rb

Fixed nil class exception for raid configuration with empty virtual disks.

LUD-534 Fixed nil exception for raid w/no virtual disk

---

lib/puppet/provider/importtemplatexml.rb

Fixed bug where removing nonraid disks was not happening for nonRAID controllers that don't
support it.

LUD-534 Fixed bug where removing nonraid disks

---

lib/puppet/provider/server_onboard/default.rb

It looks like we pass array of network objects, instead of a
single network object. Generally, this array contains only one
network object. This change addresses the handling of the input
parameter type, when a server is being onboarded.

LUD-1531 fix iDRAC onboarding with static IP address

---

lib/puppet/provider/idrac_racadm.rb
spec/unit/puppet/provider/idrac_racadm_spec.rb

After an iDrac factory reset it will report a warning banner when
logging in via ssh that says "Warning: It is recommended not to use
the default user name (root) and password as it is a security
risk.". This broke the `racadm_get` parsing and thus the
`server_onboard` idrac user password setting which uses racadm.

VXFM-2163 Fix server_onboard for default password warning

---

lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

NVMe drives may be connected directly to the PCIe bus without a
controller. However, they are passed in the `raid_configuration` with
a "fake" controller value of "Enclosure.Internal.0-1" in the
`virtualDisks` list:
raid_configuration:
virtualDisks:
- raidLevel: nonraid
physicalDisks:
- Disk.Bay.21:Enclosure.Internal.0-1
- Disk.Bay.22:Enclosure.Internal.0-1
- Disk.Bay.23:Enclosure.Internal.0-1
controller: Enclosure.Internal.0-1
configuration:
id: 94e9ea6e-80a6-4bc1-be69-541334a30e84
raidlevel: nonraid
comparator: minimum
numberofdisks: 3
disktype: requirenvme
controllerFqdd: Enclosure.Internal.0-1
mediaType: NVMe
In this case they need to be skipped in the same way as
HBA330-attached disks -- they require no configuration.

VXFM-4166 Skip NVMe drives without controllers

---

lib/puppet/provider/server_onboard/default.rb
spec/unit/puppet/provider/server_onboard/server_onboard_spec.rb

This is a fix to ensure that waiting for connection does not cause
puppet apply to fail. In isolated OOB hardware management network,
exceptions cause failure before timeout has been reached.
Additionally, the provider will also wait for the /cgi-bin/discovery
endpoint to become available to ensure that the Job does not fail
on the java-layer afterward.

VXFM-4624 server onboarding should not fail while waiting for connection

---

lib/puppet/provider/importtemplatexml.rb

Previous code had an ensure block that accidentally ate the exception
if the ImportSystemConfiguration job timed out.

VXFM-5226 Fail ImportSystemConfiguration if it times out

---

lib/puppet/provider/idrac.rb
lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

In case of NVDIMM on server, then we need to set attribute on BIOS section to enable sanitize NVDIMMs

VXFM-5951 Need to sanitize NVDIMMs during new deployment

---

lib/puppet/idrac/util.rb
lib/puppet_x/puppetlabs/transport/racadm.rb

`Net::SSH::Verifiers::Null` was removed. It looks like
`:verify_host_key => :never` is the more correct way to disable host
key verification but for Dacite release sticking with
`:verify_host_key => false` which is already in use in existing code.

VXFM-9100 Automated iDrac reset was failing due to Net::SSH changes

---

lib/puppet/provider/importtemplatexml.rb
spec/unit/puppet/provider/importtemplatexml_spec.rb

This line was creating problems in the idrac config file causing deployments to fail because it was setting a bad value for hddseq as thats already set with pxe_boot options
Requires Merging from these PR's at same time:
https://github.com/dell-asm/dell-asm-util/pull/158
https://github.com/dell-asm/asm-deployer/pull/3145
https://github.com/dell-asm/asm-core/pull/5433

VXFM-8464 Make changes to support raid boot for nodes in a deployment

---

lib/puppet/provider/importtemplatexml.rb
spec/fixtures/satadom_boot_sources_1.json
spec/unit/puppet/provider/importtemplatexml_spec.rb

Some new satadom were returning a different device string that did not contain the words /SATADOM/ and as such were unrecognized

VXFM-9988 new sata dom returned different device string

---

lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
lib/puppet/type/idrac_fw_installfromuri.rb

Support staging (downloading) of the firmware on all the nodes first. If this operation is successfull and proceed with rack firmware upgrade, In second stage need to schedule reboot job on the servers to have firmware applied

VXFM-9700 New orchstration flow to support whole Rack RCM update with downtime

---

lib/puppet/provider/idrac_fw_installfromuri/wsman.rb

Failed to install SAS firmware as logic to map downloaded job from pre_firmware operation is not matching with the firmware list

VXFM-10639 Disruptive firmware operation failed to install SAS firmware
