dell-asm/dell-idrac

- lib/puppet/provider/importsystemconfiguration/default.rb
- lib/puppet/provider/importtemplatexml.rb
- lib/puppet/type/importsystemconfiguration.rb
NEEDS TO BE MERGED WITH:
https://github.com/dell-asm/asm/pull/215 and https://github.com/dell-asm/asm-deployer/pull/760
as well as corresponding asm-core changes
> Support for advanced bios settings with clone from reference

- lib/puppet/provider/idrac.rb
- lib/puppet/provider/importsystemconfiguration/default.rb
- lib/puppet/provider/importtemplatexml.rb
- lib/puppet/type/importsystemconfiguration.rb
MUST BE MERGED WITH: https://github.com/dell-asm/asm/pull/218 and https://github.com/dell-asm/asm-deployer/pull/766
> Ensure RAID is enabled on teardown.

- lib/puppet/provider/idrac.rb
- lib/puppet/provider/importtemplatexml.rb
- spec/fixtures/FOOTAG.xml
- spec/fixtures/FOOTAG_original.xml
- spec/unit/puppet/provider/importtemplatexml_spec.rb
I also slipped in a few Ruby formatting fixes.
> Bios settings now removed if they don't exist on target

- lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
Return the object instead of the path, this will protect from a
file being garbage collected too soon
> ASM-3534 TempFile garbage collect fix

- lib/puppet/provider/importtemplatexml.rb
1) 'none' was being passed from the UI for read only settings, and we were not correctly ignoring. 
2) If the value is 'none' we should explicitly remove it from the xml
> ASM-3590 Now correctly applying read only bios settings when given

- lib/puppet/provider/importtemplatexml.rb
1) Now checking target server's BIOS Enumeration if we should apply the bios setting from the reference config
2) Value for 'none' has been changed to n/a from the Java side
> Small changes on BIOS settings checks.

- lib/puppet/provider/importsystemconfiguration/default.rb
- lib/puppet/provider/importtemplatexml.rb
IMPORTANT: Merge with https://github.com/dell-asm/asm-deployer/pull/860 and https://github.com/dell-asm/asm-core/pull/1396
> Support for none w/ Raid Config option in target boot device

- lib/puppet/provider/importsystemconfiguration/default.rb
- lib/puppet/provider/importtemplatexml.rb
- only apply bios settings if they appear in BIOS enumeration
- support for target boot type of none w/ raid configuration
- remove BiosBootSeq from xml if boot type of none
- add clear lc job queue after idrac reset
> ASM-3603 improve import from reference sever reliability

- lib/puppet/idrac/util.rb
- lib/puppet/provider/exporttemplatexml.rb
- lib/puppet/provider/idrac.rb
- lib/puppet/provider/importsystemconfiguration/default.rb
- lib/puppet/provider/importtemplatexml.rb
- spec/unit/puppet/provider/exporttemplatexml_spec.rb
- spec/unit/puppet/provider/importtemplatexml_spec.rb
- wait for all LC jobs to complete prior to import/export
- retry if LC claims import/export job is already running
> ASM-3683 workarounds for import/export failures

- lib/puppet/provider/importtemplatexml.rb
(cherry picked from commit b6a2f70dd8ac0be903814221bcd676029b20f330)
https://jira.labs.dell.com/browse/ASM-3869
Original PR:
https://github.com/dell-asm/dell-idrac/pull/159
> Fixed bad code that breaks during setting up offloads on nics

- lib/puppet/provider/importtemplatexml.rb
- spec/unit/puppet/provider/importtemplatexml_spec.rb
IMPORTANT: MERGE WITH https://github.com/dell-asm/asm-core/pull/1740
> Added support for external raid config

- lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
Pass in the object instead of the path to the method that uses the
config xml for WSman calls.  If the calls fail (sometimes after retries),
then print out the config file for debugging
> ASM-4110  Make sure Tempfile xml is used before GC

- lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
Per email from Tex, the OS_Collector is also a direct update,
we were trying to schedule this and it was failing.  Also, Idrac
and Lifecycle should be run together first before anything else
> ASM-4683  Issue with scheduling job queue

- Gemfile
- lib/puppet/provider/importtemplatexml.rb
Updated XPath for searching the attribute. Now checking in specific FQDD for the attributes that needs to be skipped for Intel NICS
> ASM-5449 Import Config XML for server having both Intel and Broadcom nic failing

- lib/puppet/provider/importtemplatexml.rb
VSAN supporting changes for iDRAC. Update CurrentControlProperty to HBA / RAID based on VSAN property
> ASM-5561 Server Puppet module changes for Phase 1 vSAN support for RA HCL

- lib/puppet/provider/importtemplatexml.rb
If ImportSystemConfig continues to have pending system configuration,
after a JID_CLEARALL and retry, issue a JID_CLEARALL_FORCE
> ASM-5892 Pending systemconfig failures

- lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
We need to monitor the end-state statuses on an individual basis.
Direct update components will finish with "Completed" while staged
update components will finish with "Scheduled" when we wait for
a user to manually perform the restart
> ASM-5883 Firmware updates failing when force_restart not selected

- lib/puppet/idrac/util.rb
> Branch merge 820 to master for dell-idrac

- lib/puppet/provider/importtemplatexml.rb
@gavin-scott please review and merge. thx
> Branch merge 820 to master dell idrac 43

- lib/puppet/provider/importtemplatexml.rb
@gavin-scott Please review and merge.
> Branch merge 820 to master dell idrac 39

- lib/puppet/provider/importtemplatexml.rb
@gavin-scott  Looks like dell-idrac can be automatically merged into master. Would you review and approve?
> Branch merge 820 to master dell idrac 47

- lib/puppet/idrac/util.rb
- lib/puppet/provider/importtemplatexml.rb
> ASM-6005 Extend idrac waits

- lib/puppet/idrac/util.rb
- lib/puppet/provider/importtemplatexml.rb
Reverts dell-asm/dell-idrac#209
> Revert "ASM-6005 Extend idrac waits"

- lib/puppet/provider/importtemplatexml.rb
Added support for boot_device "VSAN_AHCI" where Embedded SATA mode will be set to AHCIMode and SATA Disk 1 will be added as first disk in HDD Sequence. This will enable OS installation of first SATA Disk
> ASM-6387 ASM to support Urgent Fury vSAN RA

- lib/puppet/provider/importtemplatexml.rb
@sushilrai @jkrauskopf please review and merge the PR for 821 to master forwarding changes. Thx. SZL
> Branch merge 820 to master dell idrac 62

- lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
Use WsMan library for running firmware update commands in order
to properly handle escaping of special characters and errors
> ASM-6656 Use Wsman library for firmware update

- lib/puppet/provider/importtemplatexml.rb
> ASM-6387 BiosBootSeq was being set even if unchanged

- lib/puppet/provider/importtemplatexml.rb
@gavin-scott seems that this is new and no conflict, do you want to merge?
> Branch merge 820 to master dell idrac 98

- lib/puppet/provider/importtemplatexml.rb
@gavin-scott dell_idrac forward merge request, please review.
> Branch merge 820 to master dell idrac 99

- lib/puppet/provider/checkjdstatus.rb
- spec/unit/puppet/provider/checkjdstatus_spec.rb
In order to have better test coverage I was able to validate existing
tests and write new tests. SimpleCov shows 100% lines covered now.
> [MAINT] check jd status spec refactor

- lib/puppet/provider/importtemplatexml.rb
@sushilrai @aimers1975 @jkrauskopf  This is Shaorong. Please review and approve this 8.2.1 to 8.3.0 forward merge PR. Thx.
> Branch merge 820 to master dell idrac 113

- lib/puppet/provider/importtemplatexml.rb
- spec/unit/puppet/provider/importtemplatexml_spec.rb
Conditional was incorrect causing us to create the VD with an
empty set of disks
> ASM-7582 Do not create VD without any disks

- lib/puppet/provider/importtemplatexml.rb
- spec/unit/puppet/provider/importtemplatexml_spec.rb
Several changes to the xml munging when doing deployments to S130.
* We will not just run the same xml config file up to three times
* Remove the RaidinitConfig setting for S130
* When doing s130 from AHCI,ATA do a full find and replace on the
xml file to anticipate what the new controller schemas are going
to be after the embedded sata mode is changed
* Set SecurityFreeze and WriteCache to Disabled
* Do not nest the physical disks within an enclosure
> ASM-8077 Fixed S130 RAID deployments

- lib/puppet/provider/importtemplatexml.rb
- spec/unit/puppet/provider/importtemplatexml_spec.rb
Updated backend to support RAID configuration passed into hardware configuration for local flash storage servers.
> LUD-222 Support BOSS boot device which includes scale io RAID config.

- .gitignore
- .travis.yml
- Gemfile
- spec/spec_helper.rb
Upgrade ruby and gems to match latest environment based on puppet
5.4.0
> LUD-114 Upgrade ruby version and gems

- lib/puppet/provider/importtemplatexml.rb
Fix bug with null exception in non-ScaleIO case for local flash storage. Need to create the full RAID config when the scale IO raid configuration is not present.
> LUD-407 Fix bug with null exception in non-ScaleIO case

- lib/puppet/provider/importtemplatexml.rb
nonRAID configuration was failing as logic for determining if non-raid disk was requested was wrong, and an extra nonRAID config was getting created.  Also, we remove the nonRAID config when the
controller does not support it, as in the case of HBA330 Mini.
> LUD-534 Deployments are failing for 13g nonRAID configurations

- lib/puppet/provider/server_onboard/default.rb
- spec/unit/puppet/provider/server_onboard/server_onboard_spec.rb
@gavin-scott @aroberson @sushilrai @naveenhirebeeldell 
kindly review and merge .
> Fixed : VXFM-2937:Setting new creds during rack initial configuration

- lib/puppet/provider/importtemplatexml.rb
@gavin-scott @saxens7  Can you please review this PR?
> VXFM-5186 - Modifying importtemplatexml to support UEFI

- lib/puppet/provider/idrac_fw_installfromuri/wsman.rb
wait for LC status to be ready before moving onto the next FW package
> VXFM-6182c wait for LC status to be ready before moving onto the next FW package
